networks:
  default:
    driver: bridge
    name: roboshop

services:
  mongodb:
    image: praneeth2701/mongodb:v2
    container_name: mongodb
  # catalogue:
  #   image: praneeth2701/catalogue:v1
  #   container_name: catalogue
  #   environment:
  #     MONGO: "true"
  #     MONGO_URL: "mongodb://mongodb:27017/catalogue"
  #   depends_on: 
  #   - mongodb
  # redis:
  #   image: praneeth2701/redis:v1
  #   container_name: redis
  # user:
  #   image: praneeth2701/user:v1
  #   container_name: user
  #   environment:
  #     MONGO: "true" 
  #     REDIS_URL: "redis://redis:6379" 
  #     MONGO_URL: "mongodb://mongodb:27017/users"
  #   depends_on: 
  #   - redis
  #   - mongodb
  # cart:
  #   image: praneeth2701/cart:v1
  #   container_name: cart
  #   environment:
  #     REDIS_HOST: "redis" 
  #     CATALOGUE_HOST: "catalogue" 
  #     CATALOGUE_PORT: "8080"
  #   depends_on: 
  #   - catalogue
  #   - redis
  # mysql:
  #   image: praneeth2701/mysql:v1
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: RoboShop@1
  # shipping:
  #   image: praneeth2701/shipping:v1
  #   container_name: shipping
  #   environment:
  #     CART_ENDPOINT: "cart:8080" 
  #     DB_HOST: "mysql"
  #   depends_on:
  #   - mysql
  #   - cart
  # rabbitmq:
  #   image: praneeth2701/rabbitmq:v1
  #   container_name: rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "roboshop" 
  #     RABBITMQ_DEFAULT_PASS: "roboshop123"
  # payment:
  #   image: praneeth2701/payment:v1
  #   container_name: payment
  #   environment:
  #     CART_HOST: "cart"
  #     CART_PORT: "8080"
  #     USER_HOST: "user"
  #     USER_PORT: "8080"
  #     AMQP_HOST: "rabbitmq"
  #     AMQP_USER: "roboshop"
  #     AMQP_PASS: "roboshop123"
  #   depends_on:
  #   - rabbitmq
  #   - user
  #   - cart
  # frontned:
  #   image: praneeth2701/frontend:v1
  #   container_name: frontend
  #   ports:
  #   - "80:80"
  #   depends_on:
  #   - catalogue
  #   - user
  #   - cart
  #   - shipping
  #   - payment

    
